### ISSUE TITLE
[Konzept] On-the-fly Metadata Edit

### ISSUE THREAD

**Issue by phiku** [Madek/madek-webapp#69]
Offene Punkte sind mit [x] referenziert. 

## Übersicht

Metadaten sollen künftig schneller editiert werden können. Deshalb soll in der Box, wo die Eintrage aufgelistet werden, ein Metadaten Editor erscheinen sobald man Einträge auswählt [1][2]. Dieser entspricht mehr oder weniger dem Metadaten Editor wie wir ihn schon haben, ist aber direkt eingebettet in die Box. Beispiel für einen selektierten Eintrag:

![bildschirmfoto 2016-12-15 um 11 12 31](https://cloud.githubusercontent.com/assets/16756048/21220411/0680fd3a-c2b9-11e6-9a3f-09029bb56572.png)

Der Editor funktioniert unterschiedlich, je nachdem ob man einen oder mehrere Einträge ausgewählt hat. Für mehrere ausgewählte Einträge [3] sind wir im Batch-Modus:

![bildschirmfoto 2016-12-15 um 11 12 39](https://cloud.githubusercontent.com/assets/16756048/21220489/592b495a-c2b9-11e6-961e-74b4de54de40.png)

Da die Batchverarbeitung komplexer ist, wird sie nicht überall angeboten. Wo soll der Editor erscheinen:
- Für einzelne ausgewählte Einträge überall wo man Einträge in der Box auswählen kann. 
- Für mehrere ausgewählte Einträge nur in Sets und Stapelverarbeitungsset.

## Kontext

- Dieser Editor soll den alten Batch Editor ersetzen. 
- Den Metadaten Editor für einen einzelnen Eintrag wird es wahrscheinlich noch geben. 
- Das Zwischenablage Set soll weiterhin gemacht werden, da es das zusammensammeln von Einträgen besser erlaubt. Wenn man dieses Set öffnet, wird der neue Editor jedoch zum bearbeiten verwendet. 
- Die Permissions werden eventuell als "Kontext" aufgelistet, mit einem Link auf das existierende Permissions Formular, welches zu komplex scheint, um es in dem neuen Editor einzubauen. 
- Der neue Editor funktioniert für Medieneinträge und für Sets. Es wäre eventuell sogar denkbar, dass dieser irgendwann erlauben würde, gemeinsame Metadaten von Sets und Medieneinträgen gleichzeitig zu erfassen. 

## Interaktion

Wenn der Editor geöffnet wird, ist per Default der erste Kontext ausgewählt [5]. Die Einzelnen Keys werden aufgelistet mit ihren Werten:

![bildschirmfoto 2016-12-15 um 11 59 08](https://cloud.githubusercontent.com/assets/16756048/21222976/0c84df7e-c2c5-11e6-8074-e90608184764.png)

Wenn man einen Key anklickt, wird er editierbar. Zudem wird bei allen Einträgen der Wert für den selektierten Metakey gerade unter dem Thumbnail angezeigt [6]: 

![bildschirmfoto 2016-12-15 um 11 59 16](https://cloud.githubusercontent.com/assets/16756048/21223004/3e23700e-c2c5-11e6-98cb-e40d1e035a1d.png)

Wenn man einen Wert eingibt, dann wird dieser automatisch gespeichert nach einer kurzen Wartezeit. Dazu gibt es drei Zustände. Sobald man einen Wert ändert, sind die Metadaten des Eintrags als "changed" vorgemerkt. Nach einem Timeout wird der Eintrag automatisch gespeichert und geht somit in "saving" über. Sobald das Speichern erfolgreich war, geht der Eintrag in "saved" über [4]:

![bildschirmfoto 2016-12-15 um 11 59 23](https://cloud.githubusercontent.com/assets/16756048/21223021/59809516-c2c5-11e6-943a-af3f3b110315.png)

Das automatische Speichern gibt es nur wenn man einzelne Einträge selektiert. Wenn man mehrere hat, ist man automatisch in der Batch Verarbeitung. Es wäre zu heikel, Änderungen an mehreren Einträgen automatisch zu speichern. Man wählt explizit aus, ob man die Ändrungen auf alle Einträge im Set oder nur auf die selektierten anwenden möchte:

![bildschirmfoto 2016-12-15 um 12 57 21](https://cloud.githubusercontent.com/assets/16756048/21223180/213ffed4-c2c6-11e6-85e1-bdc8ad96cfc6.png)

## Vorteile

1. Man kann während dem Batch Editieren die Auswahl ändern.
2. Wenn man zum Beispiel den Wert "Titel" ändern will bei mehreren Einträgen, kann man den ersten Eintrag anklicken, auf den Wert "Titel" klicken, einen Titel eingeben, welcher automatisch gespeichert wird. Wenn man nun keinen anderen Wert anklickt, bleibt dieser geöffnet, auch wenn man den nächsten Eintrag anklickt. Bei diesem kann man dann sofort den nächsten Titel eingeben. 
3. Weniger klickts, weniger Ladezeiten.
4. Man kann die schon existierenden verschiedenen Anzeige Mode (gekachelt, klein, gelistet) gerade wiederverwenden im Batch Modus und kann somit mehr Information sehen. 
5. Man kann die verschiedenen Werte für einen Metakey besser vergleichen.  

## Nachteile

1. Automatisches Speichern könnte heikel sein, da es kein "Rückgängig" gibt. Allerdings werden nur immer einzelne Daten editiert, wodurch Fehler kaum auftreten können [4]. 
2. Wenig Platz, schwierigeres Layouting.

## Offene Punkte / Details

[1] Wie öffnet sich der Editor:
Soll der Editor erscheinen, wenn man Einträge anclickt, oder soll er explizit via Button einfach eingeblendet werden. Vortail bei anclicken: Es ist einfacher für den Benutzer. Nachteil: Sobald sich der Editor öffnet, haben die Medieneinträge weniger Platz, wodurch der soeben ausgwählte Eintrag auf eine oder mehrere Zeilen nach unten springt, was irritierend ist für den Benutzer. 

[2] Wie kann man Einträge auswählen:
Das Auswählen der Einträge funktioniert im Moment via Checkbox. Diese ist etwas umständlich, da sie nur erscheint, wenn man mit der Maus über den Eintrag fährt. Wenn man auf den Eintrag klickt, wird er geöffnet in der Detail Ansicht. Möglichkeiten für die Auswahl wären:
a) Der Eintrag wird selektiert wenn man ihn anclickt. Falls man ihn in der Detail ansicht öffnen will, muss man auf ein Icon klicken, welches da erscheinen würde, wo jetzt die Checkbox ist. 
b) Die Checkbox wird über das Thumbnail des Eintrags gelegt, so dass es immer ersichtlich ist.
c) Wenn man mit der Maus über einen Einträg fährt, wird das Thumbnail halbtransparent mit weiss ausgeblendet und darauf erscheinen zwei Links, einerseits "öffnen", andererseits "selektieren".

[3] Wie kann man mehrere Einträge auswählen:
Wenn man das auswählen belässt wie es ist, mit der Checkbox, dann erübrigt sich diese Frage. Eine Alternative wäre jedoch, dass man durch klicken auf das Thumbnail einen Eintrag auswählen kann und mit der gehaltenen Shift Taste mehrere auswählen kann. Der Vorteil ist, dass man durch anklicken eines einzelnen nicht zuerst die anderen deselektieren muss. Der Nachteil ist, wenn man die Shift Taste vergisst, ist die Selektion verloren wenn man einen weiteren anklickt. 

Ein Vorschlag von Tashi war zudem, das Selektieren per Seite zu ermöglichen.

[4] Fehler bei automatischem Speichern: 
Die wichtigste Frage beim automatischen Speichern ist, ob der Benutzer schon den nächsten Wert editieren darf, solange das Speichern noch nicht erfolgreich ist. 

[5] Anzeige der Kontexte:
Wahrscheinlich ist es sinnvoll, die Kontexte mit einem Accordion darzustellen. 

[6] Anzeige des Metakey Wertes beim Thumbnail:
Es ist noch unklar, wo genau der Wert angezeigt werden soll. Möglichkeiten: 
a) Dort wo der Titel steht. Es könnte jedoch sinnvoll sein, wenn man den Titel immer sieht. 
b) Dort wo der Untertitel steht. 
c) An einem anderen Ort. 

[7] Batch Schlagwörter: 
Es ist noch unklar, wie sich die Batch Aktionen ändern werden bei komplexeren Metakeys, wie zum Beispiel Schlagwörter. Möglichkeiten:
1. Wert x bei allen hinzufügen. 
2. Wert x bei allen löschen. 
3. Wert x y z bei allen neu setzen.

[8] Scrolling: 
Es ist eine Herausforderung, den Kontext Editor am richtigen Ort anzuzeigen. Insbesondere, wenn man zum Beispiel auf der sechsten Seite bei vielen Einträgen einen selektiert, ist es nicht optimal, wenn der Editor zuoberst auf der Seite angezeigt wird, da man ihn gar nicht sieht. Eine Möglichkeit wäre, dass er immer per Page angezeigt wird. Die andere wäre, dass er immer mitscrolllt. Das wiederum ergibt das Problem, dass wenn der Editor wegen komplexen Metadaten höher ist als der Browser, müsste man innerhalb des Editors auch wieder scrollen können.

**Comment by niknoilich** [comment]
[ ] Jawohl

**Comment by niknoilich** [comment]
Vorschläge zu den Themen [5] Anzeige der Kontexte und [7] Batch Schlagwörter sind hier zu finden: http://mqd8qg.axshare.com/#g=1&p=test
